openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /coin/:coinId:
    get:
      summary: Returns a list of rates.
      description: Returns a list of rates for the coinId passed in query param
      responses:
        '200':    # status code
          description: A JSON Object of list of rates for the coinId.
          content:
            application/json:
              schema: 
                type: Object
                items: 
                  type: string
        '400':    # status code
          description: coinId not valid should be in ['BTC','USD'].
        '500':
          description: Internal Server Error